# Generated by Django 3.1.6 on 2021-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_user',
            field=models.BooleanField(default=False),
        ),
    ]
