# Generated by Django 3.1.6 on 2021-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
