# Generated by Django 3.1.6 on 2021-03-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210303_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='OHIP',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
